### ISSUE TITLE
BUG: not working 

### ISSUE THREAD

**Issue by Tophatven** [pashpashpash/manga-reader#14]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

> use this command to get the details (for bash shell)

```bash
echo "- OS: $(uname)"
echo "- Browser: $(xdg-settings get default-web-browser)"
echo "- Version: $(
eval "$(xdg-settings get default-web-browser | cut -d'.' -f1 | xargs -I {} which {}) --version"
)"
```

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rishi23root** [comment]
i think this is a false positive, reopen if there is any info to share.
